// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhcDulQNi-KfPhvhgehOYCJcFkW_DIAo',
    appId: '1:998201512406:web:7f664726faf4ef52fc9477',
    messagingSenderId: '998201512406',
    projectId: 'restaurante-76df3',
    authDomain: 'restaurante-76df3.firebaseapp.com',
    storageBucket: 'restaurante-76df3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvYmt5Ky_ze-j1ykL9_EBGE_iwYWLeJ8',
    appId: '1:998201512406:android:a9a38fe83d5e8cc1fc9477',
    messagingSenderId: '998201512406',
    projectId: 'restaurante-76df3',
    storageBucket: 'restaurante-76df3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_-WNsiDXXbguJYZt5UViPI2WB6WGFQk',
    appId: '1:998201512406:ios:da6d7e10b92f6e68fc9477',
    messagingSenderId: '998201512406',
    projectId: 'restaurante-76df3',
    storageBucket: 'restaurante-76df3.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT_-WNsiDXXbguJYZt5UViPI2WB6WGFQk',
    appId: '1:998201512406:ios:da6d7e10b92f6e68fc9477',
    messagingSenderId: '998201512406',
    projectId: 'restaurante-76df3',
    storageBucket: 'restaurante-76df3.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnhcDulQNi-KfPhvhgehOYCJcFkW_DIAo',
    appId: '1:998201512406:web:a6aca2c5466cf5d6fc9477',
    messagingSenderId: '998201512406',
    projectId: 'restaurante-76df3',
    authDomain: 'restaurante-76df3.firebaseapp.com',
    storageBucket: 'restaurante-76df3.appspot.com',
  );
}
