// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5d7F5cjlC4E-bLnid0Dqx8noz-QgqaM',
    appId: '1:291734082643:web:7f664726faf4ef52fc9477',  // Cambia esto por tu propio appId
    messagingSenderId: '291734082643',
    projectId: 'restauranteb-bb6a4',
    authDomain: 'restauranteb-bb6a4.firebaseapp.com',
    storageBucket: 'restauranteb-bb6a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX5d7F5cjlC4E-bLnid0Dqx8noz-QgqaM',
    appId: '1:291734082643:android:e608291e31f1a7428be2a6',  // Actualiza con tu nuevo appId
    messagingSenderId: '291734082643',
    projectId: 'restauranteb-bb6a4',
    storageBucket: 'restauranteb-bb6a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX5d7F5cjlC4E-bLnid0Dqx8noz-QgqaM',
    appId: '1:291734082643:ios:da6d7e10b92f6e68fc9477',  // Cambia esto por tu propio appId
    messagingSenderId: '291734082643',
    projectId: 'restauranteb-bb6a4',
    storageBucket: 'restauranteb-bb6a4.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX5d7F5cjlC4E-bLnid0Dqx8noz-QgqaM',
    appId: '1:291734082643:ios:da6d7e10b92f6e68fc9477',  // Cambia esto por tu propio appId
    messagingSenderId: '291734082643',
    projectId: 'restauranteb-bb6a4',
    storageBucket: 'restauranteb-bb6a4.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5d7F5cjlC4E-bLnid0Dqx8noz-QgqaM',
    appId: '1:291734082643:web:a6aca2c5466cf5d6fc9477',  // Cambia esto por tu propio appId
    messagingSenderId: '291734082643',
    projectId: 'restauranteb-bb6a4',
    authDomain: 'restauranteb-bb6a4.firebaseapp.com',
    storageBucket: 'restauranteb-bb6a4.appspot.com',
  );
}
